### ISSUE TITLE
Support automatic deployments via an API

### ISSUE THREAD

**Issue by ghost** [accrescent/meta#41]
I was unsure where to create this issue, so I made it here.
F-Droid and Google Play both support this feature already.

Some developers would appreaciate this functionality to reduce overhead:
https://github.com/spacecowboy/Feeder/issues/454#issuecomment-2545301356
https://github.com/d4rken-org/sdmaid-se/issues/1493#issuecomment-2541992507

**Comment by Niko4u5** [comment]
There already is an open issue about this https://github.com/accrescent/parcelo/issues/286

**Comment by ghost** [comment]
Then I will close this issue, thank you for notifying me!
